### PR TITLE
Short circuiting inner invoker 

### PR DESCRIPTION
**Pull request by kevbite**
Small PR to show example of short circuiting function for Issue #1310

### CODE REVIEW

**Comment by kevbite** [comment]
Seems we also need to set the result value as well

```
parameterHelper.SetReturnValue(returnValue);
```

Then also call `ProcessOutputParameters` to set all the values back on the binders, actually looks like more work than I originally thought.

**Comment by mamaso** [comment]
Looks like there's some value here - asp.net action filters appear to have a similar feature short-circuiting if result is set in a filter, we should try to mirror that behavior.

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Filters/ActionFilterAttribute.cs#L49

**Comment by mamaso** [comment]
Perhaps we can move that inner invoker logic to outside the invoke filters in order to light this up

**Comment by kevbite** [comment]
Would need to remove this bit of logic in the static `Create` method so it always get executed

```
if (filters.Count == 0)
 {
     return innerInvoker;
}
```

Just seems a bit hacky, would be more sensibly to just try remove that logic away

**Comment by mathewc** [comment]
Earlier versions of the code actually had a Result capability but we scaled back and removed it because it requires more design. I created #1314 to track this work.

**Comment by kevbite** [comment]
Yeah looked simple at first but then after another look it opened a bag of worms! Thanks for information I'll track the progress on  #1314

**Comment by mathewc** [comment]
Thank for sending the sketch PR though. You're right, it is a bag of worms and we have several related scenarios we want to enable with this, so we need the right design in place.

**Pull request closed without merging**
