### PR TITLE
Updated PackageLicenceExpression and Icon

### LINKED ISSUE #2571: Update build to use .net 3.1
Opened PR here: https://github.com/Azure/azure-webjobs-sdk/pull/2569

But there was an error: 
```
105dotnet.exe : Testhost process exited with error: It was not possible to find any compatible framework version
106At C:\projects\azure-webjobs-sdk-rqm4t\runtests.ps1:15 char:3
107+ & dotnet $cmd
108+ ~~~~~~~~~~~~~
109 + CategoryInfo : NotSpecified: (Testhost proces...amework version:String) [], RemoteException
110 + FullyQualifiedErrorId : NativeCommandError
111 
112The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
113 - The following frameworks were found:
114 2.0.0 at [C:\Program Files (x86)\dotnet
115\shared\Microsoft.NETCore.App]
116 3.1.8 at [C:\Users\appveyor\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
117You can resolve the problem by installing the specified framework and/or SDK.
118The specified framework can be found at:
119 - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x86&rid=win10-x86
120. Please check the diagnostic logs for more information.
121
122
123Test Run Aborted.
124
```

### PR DESCRIPTION
**Pull request by yojagad**
- Updated deprecated tags to fix nuget pack errors on .Net 3.1
- Updated build to include dotnet 3.1
- Udpated test projects target framework to 3.1 
- Fixed exception message formats in tests- Exception message format was updated for `ArgumentException` in .Net 3.1

Resolves #2571

### CODE REVIEW

**Comment by pragnagopa** [comment]
we need to move the build to 3.1 to merge this PR.

**Comment by pragnagopa** [comment]
@mhoeger - Any details on errors if the build script updated to 3.1?

**Comment by mhoeger** [comment]
@pragnagopa - Error captured here https://github.com/Azure/azure-webjobs-sdk/issues/2571

**Comment by pragnagopa** [comment]
Thanks @mhoeger - updated the build to include 2.1 and 3.1

**Comment by pragnagopa** [comment]
@mhoeger / @brettsam - having both 2.1 and 3.1 unblocks the build. Please review.

**Comment by brettsam** [comment]
I don't understand the original bug :-) Why do we need to move this to 3.1?

**Comment by yojagad** [comment]
@brettsam The original intent of the PR is to update the deprecated tags (PackageUrl and PackageIconSomething) for nuget pack errors. I believe the previous attempt at doing so was giving errors  because the build was not in 3.1

**Comment by mhoeger** [comment]
Some more context: https://github.com/Azure/azure-webjobs-sdk/pull/2560#issuecomment-689038585

**Comment by pragnagopa** [comment]
Thanks for adding more context @mhoeger and @yojagad !

@brettsam - as of now pack fails locally if using .Net 3.1, trying to address this  :)

**Review by fabiocav — CHANGES_REQUESTED** [review]
Need to discuss the changes to understand the requirement as this shouldn't be needed.

**Comment by pragnagopa** [comment]
Closing as not needed. See comments in the linked issue.

**Pull request closed without merging**
