### PR TITLE
All kinds of convenience methods for creating bindings in FluentBindingRule should have an overload that accepts a factory that can process a ValueBindingContext

### PR DESCRIPTION
**Pull request by macrogreg**
This PR addresses https://github.com/Azure/azure-webjobs-sdk/issues/2488 - please see the description there.
There is is also minor code clean-up: Adding mission `#region` statements and fixing some doc comments in `FluentBindingRule`.

### CODE REVIEW

**Comment by macrogreg** [comment]
I think this PR needs a full-ci label, but I may not have permissions to assign it.
@mathewc  / @brettsam ,  could you please tag this PR accordingly?

**Comment by fabiocav** [comment]
@mathewc are you planning on looking at this? Would it help to have it assigned to a sprint/individual?

**Comment by liliankasem** [comment]
@mathewc do we still wanna review?

**Comment by mathewc** [comment]
Based on the last comment from @zmarty in issue https://github.com/Azure/azure-webjobs-sdk/issues/2488 this is still needed. I believe @macrogreg may no longer be working on this (correct me if I'm wrong!). The changes were needed for the Availability Monitoring extension but in that repo https://github.com/Azure/azure-functions-availability-monitoring-extension I don't see any source code?

Work remaining in my mind for this would be to add tests for the new proposed overloads, and to test this out via a private nuget with the extension before committing. There was if I remember a hacky workaround they had to use, so we'd test that they can remove that and use the new overloads successfully.

**Pull request closed without merging**
