### PR TITLE
Restore non-graceful shutdown on CancellationToken for QueueTrigger.

### PR DESCRIPTION
**Pull request by davidmatson**
Splitting from the other PR so we can discuss the JobHost parts separately.

(For now, this PR includes the other two commits from the first PR, but I can update this PR to include only one commit once the other commits are merged in.)

### CODE REVIEW

**Comment by davidmatson** [comment]
@fabiocav, @brettsam - thoughts on this PR? Currently, we're passing in CancellationToken.None, which seems like a shame. (It's my fault from years back - I couldn't figure out what a cancellation token here would do at the time.)

**Comment by azfuncgh** [comment]
In an effort to clean up the repository, we're closing stale PRs. If you feel this is still relevant, please reopen the PR and we'll work on moving this forward. Thank you for your contribution!

**Comment by davidmatson** [comment]
@azfuncgh says to reopen the PR if I think it's still relevant, but it doesn't indicate how to do so.

@fabiocav or @brettsam - can you help?

**Pull request closed without merging**
