### PR TITLE
Bump app insights dependencies

### LINKED ISSUE #2900: Update dependency on Microsoft.ApplicationInsights
A new [version](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nuget.org%2Fpackages%2FMicrosoft.ApplicationInsights%2F2.21.0&data=05%7C01%7CLove.Josh%40microsoft.com%7Cee33cb46b71c4d831e7808da770a8908%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637953184376476224%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UV6kova49ZDTzhCJDIF3Yv4jFwBQwgm1DifDaK07Qmc%3D&reserved=0) of the App Insights library has been released that adds additional support for the new Service Bus library. In order for Service Bus extension users to benefit from these changes, we would need to update the dependency version used in the WebJobs SDK, which would in turn pull up the version used by the Functions host.

### PR DESCRIPTION
**Pull request by ilmax**
Fixes #2900

I've updated all the application insights dependencies to 2.21 and the SnapshotCollector to the latest stable 1.4.3, anything else that needs to be done here @JoshLove-msft ?

### CODE REVIEW

**Comment by ilmax** [comment]
@mathewc By any chance, can you have a look at this one?

**Comment by mathewc** [comment]
Looks good to me - @brettsam see any issues here? I notice that even the Functions Host hasn't pulled in this new version yet - [it's still on 2.20](https://github.com/Azure/azure-functions-host/blob/438b1d4daf431dccefbe09d76f2f96fb8acdd694/src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj#L66).

**Comment by brettsam** [comment]
I swear there was a reason we had to abandon updates to this package -- maybe a dependency could cause v3 to break if we took it due to some major bump?

Let me try to figure it out...

**Comment by brettsam** [comment]
That doesn't seem to be it -- we may have just started doing these changes directly in azure-functions-host for convenience. That meant we didn't have to do a release, etc, just to bump to a newer version.

@ilmax -- I assume the end-goal for these versions to be in Functions production?

**Comment by brettsam** [comment]
n/m -- appears to be a WebJobs requirement based on the linked issue. Right now, customers should be able to directly reference the required App Insights nuget packages in their WebJobs app; nothing should be preventing that...

Unfortunately, our release flow for these packages is slow due to the dependency in Functions production. So once this is in, the flow needs to be:

1. We should probably follow-up and sever the project dependency on WebJobs.Host so we don't need a full release of everything just for this. Instead, we can have it depend on the last deployed nuget...
2. Get an official build and move it all the way to host in v3.x and dev.
3. Wait until this makes its way to production.
4. Then publish this package on nuget.

**Comment by brettsam** [comment]
The build fails here b/c of some test dependencies. Let me pull this and fix it up.

**Comment by ilmax** [comment]
> n/m -- appears to be a WebJobs requirement based on the linked issue. Right now, customers should be able to directly reference the required App Insights nuget packages in their WebJobs app; nothing should be preventing that...
> 
So we just need to reference the right version of AppInsights to fix the issue? I'd like still to update AppInsight package here to do the right thing by default, since the old ServiceBus library is deprecated and the new one isn't supported properly by the referenced version of the AppInsights library

**Comment by brettsam** [comment]
Any direct reference in your project will override what we reference here and should get you running with the latest; this shouldn't be blocking anyone. It's not required that we update (although it's a nicer experience).

That being said, I've created a new PR to update b/c it was easier to manage from testing, etc. I'm going to close this one in favor of that: https://github.com/Azure/azure-webjobs-sdk/pull/2916

**Comment by JoshLove-msft** [comment]
> Any direct reference in your project will override what we reference here and should get you running with the latest; this shouldn't be blocking anyone. It's not required that we update (although it's a nicer experience).

Is this true for the Isolated worker? I was under the impression that users couldn't influence the dependencies used there.

**Comment by ilmax** [comment]
> Is this true for the Isolated worker? 

I updated my webjobs and referenced the 2.21 version of application insights, but still the issue is not resolved, within application insights I still don't have end to end tracing of service bus messages.

@brettsam Any updates on #2916? This is causing real issues to customers. Any ETA on when the PR one can be merged an a new version of the WebJob SDK be released?

**Comment by brettsam** [comment]
@ilmax -- to be clear, you are running a WebJobs app, not a Functions app?

You may need to explain what you're trying to do. WebJobs and Functions don't do much with SB tracing so if updating to 2.21.0 didn't work, we may need to follow up with SB and App Insights teams.

Next release of Functions will include 2.21.0 -- https://github.com/Azure/azure-functions-host/pull/8838

**Comment by ilmax** [comment]
>@ilmax -- to be clear, you are running a WebJobs app, not a Functions app?

Correct.

In order to get it working I had to add to every project an additional reference (Microsoft.ApplicationInsights.DependencyCollector v 2.21.0) that's actually where the code for dealing with dependency is.

So it can be worked around, it just takes times, it would be much easier to reference the correct AI version in the sdk.

**Comment by brettsam** [comment]
Thanks for confirming you were able to get it working.

The commit is in, but it takes a while (a month maybe) before it can be released to nuget.org as it needs to be released globally in Functions production first.

**Pull request closed without merging**
