### PR TITLE
Refactoring builder APIs, introducing IWebJobsBuilder, moving extension methods

### PR DESCRIPTION
**Pull request by fabiocav**

### CODE REVIEW

**Comment by fabiocav** [comment]
Initial work for the configuration updates planned.

This initial set of changes introduce a different builder pattern, with WebJobs services added to the `IWebJobsBuilder` instance returned (when working with `IServiceCollection`) or provided when configuring the host (from `IHostBuilder`).

**Comment by brettsam** [comment]
I just noticed that this was WIP -- but if you have a decent stopping place (which it looks like this may be), I'd suggest just getting it in.

**Comment by mathewc** [comment]
I'll spend an hour or so getting the tests running, then I'll update the PR. Hope is to get this in by afternoon.

**Comment by fabiocav** [comment]
Sounds good. That being the case, I'll merge this and publish packages to MyGet so you have these changes and we don't have to wait for the configuration updates.

**Pull request merged**
