### PR TITLE
Adding support for MSI with Service bus

### PR DESCRIPTION
**Pull request by varadhan3n90**
Removed ServiceBusAccount class and merged it with MessagingProvider. ServiceBusAccount was only used to handle connection string by getting it from configuration, if it was not explicitly passed in ServiceBusOptions. With that merged into MessagingProvider, it is easier to use MSI and create a service bus connection.

### CODE REVIEW

**Comment by varadhan3n90** [comment]
Can someone help me with the continuous-integration?

**Comment by AnthonyDewhirst** [comment]
is there any update on this? Using MSI everywhere in our code base

**Comment by shobhitmishra** [comment]
Is there an update on this? I want to pull the connection string from Keyvault instead of appsettings. I want to use these strings in ServiceBusAccount. Is it possible?

**Comment by azfuncgh** [comment]
In an effort to clean up the repository, we're closing stale PRs. If you feel this is still relevant, please reopen the PR and we'll work on moving this forward. Thank you for your contribution!

**Pull request closed without merging**
