### PR TITLE
Remove storage emulator checks

### PR DESCRIPTION
**Pull request by xt0rted**
This isn't really meant to be merged, more to open the discussion brought up in #53.

Based on the comment by @davidebbo I removed the checks and was able to use blob and queue triggers with the storage emulator.

This is my full test app https://github.com/Azure/azure-webjobs-sdk/issues/53#issuecomment-215989639

I then used the [Azure Storage Explorer](http://storageexplorer.com/) to add text documents to the blob container, and messages to the queue. Both actions triggered their respective job to run and output the correct contents in the console.

### CODE REVIEW

**Comment by xt0rted** [comment]
I tried running the tests to see if this change caused any issues, but I'm having more trouble doing that than making the actual change.

I keep getting errors because the projects are strong named. I turned off signing on all of the projects (and updated the `InternalsVisibleTo` on each of them) which allowed the tests to run, but I'm still getting 26 failed tests due to not having the correct environment setup for them.

Is there a CI server that can run these instead of trying to get them to all run locally?

**Comment by mathewc** [comment]
Thanks for the PR! Regarding running the tests - we have a [Development](https://github.com/Azure/azure-webjobs-sdk/wiki/Development) page in the wiki - did you follow those steps?

I tried your PR locally and got the basic Queue/Blob samples working as well - sweet. As far as a full test pass, I tried that before targeting local dev storage, but things were failing quickly. I need to try that again to remember exactly what it was. Might just be a test infrastructure issue that won't manifest itself in actual basic user scenarios. Not sure yet.

If you have a chance to try running the tests, please give it a shot.

**Comment by xt0rted** [comment]
Making those changes allowed me to run the tests, but not without issue. For starters I can't run them in ReSharper, only in the VS test runner. The issue with ReSharper is due to the strong naming which is preventing that. Even in the VS test runner I can only run them, I can't debug them.

The next issue is 24 of the tests fail.

All Tests Failed

- [SingletonEndToEndTests.cs](https://github.com/Azure/azure-webjobs-sdk/blob/4232e7e7493288405fb56c009a83e129a3a97e40/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/SingletonEndToEndTests.cs)
- [MultipleStorageAccountsEndToEndTests.cs](https://github.com/Azure/azure-webjobs-sdk/blob/4232e7e7493288405fb56c009a83e129a3a97e40/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/MultipleStorageAccountsEndToEndTests.cs)
- [ServiceBusEndToEndTests.cs](https://github.com/Azure/azure-webjobs-sdk/blob/4232e7e7493288405fb56c009a83e129a3a97e40/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ServiceBusEndToEndTests.cs)

Some Tests Failed

- [AsyncChainEndToEndTests.cs#L129](https://github.com/Azure/azure-webjobs-sdk/blob/4232e7e7493288405fb56c009a83e129a3a97e40/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs#L129)
- [ParallelExecutionTests.cs#L59](https://github.com/Azure/azure-webjobs-sdk/blob/4232e7e7493288405fb56c009a83e129a3a97e40/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ParallelExecutionTests.cs#L59)

To resolve some of these I modified the `app.config` in that project and commented out `AzureWebJobsDashboard`, `AzureWebJobsStorage`, and `AzureWebJobsServiceBus`. I then set `AzureWebJobsSecondaryStorage` to the same value as below, along with adding `ServiceBusSecondary` and setting that to the same value below. After doing this the failed count dropped to 11.

In the end the failing tests are:

- [AsyncChainEndToEndTests.cs#L129](https://github.com/Azure/azure-webjobs-sdk/blob/4232e7e7493288405fb56c009a83e129a3a97e40/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs#L129)
- [ServiceBusEndToEndTests.cs#134](https://github.com/Azure/azure-webjobs-sdk/blob/4232e7e7493288405fb56c009a83e129a3a97e40/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ServiceBusEndToEndTests.cs#134)
- [SingletonEndToEndTests.cs#256](https://github.com/Azure/azure-webjobs-sdk/blob/4232e7e7493288405fb56c009a83e129a3a97e40/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/SingletonEndToEndTests.cs#256)
- [MultipleStorageAccountsEndToEndTests.cs](https://github.com/Azure/azure-webjobs-sdk/blob/4232e7e7493288405fb56c009a83e129a3a97e40/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/MultipleStorageAccountsEndToEndTests.cs) - all tests

My environment variable are:

| Key | Value |
| --- | --- |
| AzureWebJobsEnv | Development |
| AzureWebJobsDashboard | UseDevelopmentStorage=true; |
| AzureWebJobsStorage | UseDevelopmentStorage=true; |
| AzureWebJobsServiceBus | Endpoint=sb://xt0rted.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xxxxxxxx |

Based on the results of the failing tests I don't think it's because of the change I made. For example all the tests in `MultipleStorageAccountsEndToEndTests` are failing with a 409 conflict error, `AsyncChainEndToEndTests` fails because the `TotalBlobClientCount` is 12 instead of 13.

The `ServiceButEndToEndTests` result is:
```
Test Name:	Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusEndToEndTests.MultipleAccountTest
Test FullName:	Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusEndToEndTests.MultipleAccountTest
Test Source:	D:\GitHub\xt0rted\azure-webjobs-sdk\test\Microsoft.Azure.WebJobs.Host.EndToEndTests\ServiceBusEndToEndTests.cs : line 135
Test Outcome:	Failed
Test Duration:	0:00:18.541

Result StackTrace:	
at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusEndToEndTests.<MultipleAccountTest>d__18.MoveNext() in D:\GitHub\xt0rted\azure-webjobs-sdk\test\Microsoft.Azure.WebJobs.Host.EndToEndTests\ServiceBusEndToEndTests.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	
Assert.Equal() Failure
               ↓ (pos 5)
Expected: Test-topic-1
Actual:   Test-SBQueue2SBQueue-SBQueue2SBTopic-topic-1
               ↑ (pos 5)
```

**Comment by mathewc** [comment]
Thanks for the detailed analysis :) I'll run the tests myself as well, but I agree with you that the remaining 11 failures are unlikely due to your changes. What you've done is a great step forward and if any of the remaining issues turn out to be actual dev account issues, we can address them as follow ups, either attempting to make fixes, or deciding that such things just won't work with dev account.

I'll merge this in the morning :)

**Comment by mathewc** [comment]
Merged, thanks :)

**Comment by xt0rted** [comment]
Is there a myget feed for this project?

**Pull request closed without merging**
