### PR TITLE
Provide consistent buffering semantics for IAsyncCollector across all…

### PR DESCRIPTION
**Pull request by MikeStall**
… extension types.

Fix https://github.com/Azure/azure-webjobs-sdk/issues/921

### CODE REVIEW

**Comment by mamaso** [comment]
Tricky problem, I don't like the arbitrary in-memory buffering. However, if the user is adding massive objects I suppose they can flush in order to turn off buffering.

Why do we revert to the extension collector buffering after the first flush is called? I'd prefer to maintain the same buffering behavior to make things easier to reason about.

**Comment by MikeStall** [comment]
@mamaso  - the idea here is to provide consistent default behavior, which I expect will cover the majority of cases. Once they call Flush, the user is explicitly assuming control of the flush semantics.   Put another way, this gives them a clean way to "turn off" our automatic buffering.

**Comment by mathewc** [comment]
What should we do with this PR - it's half a year old? I don't think we have design consensus on this yet. Should we close this for now?

**Comment by mathewc** [comment]
Didn't mean to close this - meant to ask Mike if he thought we should close this.

**Comment by MikeStall** [comment]
I think we should leave this open, discuss the design, and make decision.

**Comment by fabiocav** [comment]
Bringing this up again. Should we just open a design issue for discussion and close this?

**Comment by MikeStall** [comment]
We already have an issue opened for this (https://github.com/Azure/azure-webjobs-sdk/issues/921), but any solution is technically breaking so we held off in v1. This PR is my proposal for solving it. Basically, we buffer the items.

**Comment by mathewc** [comment]
This PR is a year old. Can we close it?

**Comment by MikeStall** [comment]
@mathewc  - we should discuss.  The issue is:
1. given a specific binding type, want a consistent output flushing semantics between C#, CSX, and Node
2. want consistent output flushing semantics across different binding types.

**Comment by fabiocav** [comment]
Closing this for now. If we intend to continue working on this, let's reopen.

**Pull request closed without merging**
