### PR TITLE
Less allocatey logging for trigger details

### PR DESCRIPTION
**Pull request by Scooletz**
This PR reduces by half amount of memory allocated for logging the templatized trigger details.

### Bechmarking

For rough benchmarking purposes I simulated an Azure Queue trigger and its trigger details and used sharplab to verify the PR, see [this gist](https://gist.github.com/Scooletz/e7e9e91584e3123fee57b8a38770d6a7)

The amount of reduced memory footprint is quite high.

### CODE REVIEW

**Comment by Scooletz** [comment]
Dear maintainers, could I get your insight on the build failure? I dived into appveyor details but found no information. I might have missed something.

**Comment by Scooletz** [comment]
@brettsam @mathewc Could you take a look at the build failure?

**Comment by brettsam** [comment]
Sorry for the build failure -- we block non-team members from directly running CI and it gives a really confusing error. I've just added the label to kick it off.

**Comment by Scooletz** [comment]
Thank you @brettsam I wasn't aware of this limitation. It's green 💚

**Review by brettsam — APPROVED** [review]

**Pull request merged**
