### PR TITLE
Adding support for LogEvent to log the EventTelemetry

### PR DESCRIPTION
**Pull request by amigup**
Added implementation of Log Event to add the telemetry as EventTelemetry for defined event.

### CODE REVIEW

**Comment by amigup** [comment]
It seems that AppVeyor build is failing due to configuration issue. @brettsam / @lmolkova - Can you please fix the build pipeline?

**Comment by amigup** [comment]
Can this PR be reviewed?

**Review by lmolkova — COMMENTED** [review]
Can you please share your thoughts on how it is going to be used and why do you need it?

This can be achieved without changing anything on WebJobs side similar to https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#version-2x-and-later-2


Events do not seem to be ILogger concept and introducing them just to support ApplicationInsights events (which already can be done) does not seem like a common scenario.

**Comment by amigup** [comment]
@lmolkova - The logger should provide the capability of logging event telemetry, the way it's provide to log the metric telemetry currently. 
Currently, I'm porting lot of code to functions which requires to log events so raised this PR to incorporate the `LogEvent` implementation .

I've seen the link mentioned by you (https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#version-2x-and-later-2), but I don't want to expose two different mechanisms to log trace, exception, metric and event (via `ILogger` and `TelmetryClient` in the code base. The abstracted `ILogger` should provide all the relevant capabilities of logging to Application Insights); I believe that's why the **`LogMetric`** implementation was added (LogMetric - https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/LoggerExtensions.cs#L25  and  Application Insights - https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs#L116). based on LogMetric, I've added the implementation of `LogEvent`.

**Comment by azfuncgh** [comment]
In an effort to clean up the repository, we're closing stale PRs. If you feel this is still relevant, please reopen the PR and we'll work on moving this forward. Thank you for your contribution!

**Pull request closed without merging**
