### PR TITLE
Update ApplicationInsights SDK version

### PR DESCRIPTION
**Pull request by lmolkova**
This change updated AppInsights SDKs to the new version and removes AI-specific redundant code around W3C trace-context - it was implemented in .NET (System.Diagnostics.DiagnosticSource package)

This is draft (uses preview AppInsights and DiagnosticSource) PR and should be merged after stable version ships in ~1 week.

### CODE REVIEW

**Comment by lmolkova** [comment]
@brettsam could you please review? 
Tests fail because stable versions are not on nuget yet (will be published in afternoon)

**Review by brettsam — APPROVED** [review]
This looks good to me -- is there anything breaking here? Or did these changes just move a lot of this to DiagnosticsSource?

**Comment by lmolkova** [comment]
@brettsam thanks for the review.

> is there anything breaking here? Or did these changes just move a lot of this to DiagnosticsSource?
Exactly, nothing breaking.

If you are ok with it, can you please merge? 
I also have a few more things coming on top of it.

**Comment by brettsam** [comment]
Yep! Can you squash it down to one commit and then I'll merge it?

**Comment by lmolkova** [comment]
@brettsam done

**Comment by lmolkova** [comment]
thanks!

**Pull request merged**
