### PR TITLE
Managed identity for Storage Accounts

### PR DESCRIPTION
**Pull request by ross-p-smith**
This PR is around Feature Request #2109. There is a new ManagedIdentityStorageAccountProvider that will create a StorageAccountClient using Managed Identity. The feature is toggled by passing in the tenantId in your HostBuilder.

b.AddAzureStorage(managedIdentityTenantId: "xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx");

The StorageAccount or Connection attribute can then be used to determinethe Storage Account Name that will be connected to.

eg    [StorageAccount("stor161")]

This has been tested reading from a BlobTrigger and writing to a Queue with no Credentials in config files.

### CODE REVIEW

**Comment by ross-p-smith** [comment]
I'm getting this in the AppVeyor build - how do I go about fixing that up?

The path 'bin' specified in the 'TestAdapterPath' is invalid. Error: The custom test adapter search path provided was not found, provide a valid path and try again.

**Comment by JSalter2013** [comment]
@ross-p-smith Any word on when this PR is likely to accepted please? It would be handy for a client project I'm working on - they'd prefer to use MSI rather than storage connection strings when wiring up config for an azure functions durable orchestration running in an ASE/service plan.

**Comment by AdamCoulterOz** [comment]
hi @fabiocav - this is needed to be able to remove passing AzureWebJobsStorage with a secret (AccountKey) in the connection string, which is not the ideal security scenario, and then requires rotation. Can we get an ETA on when this will be considered?

**Comment by DanniJuhl** [comment]
Is this still a possibility to have considered? Quite a few organisations that I speak with, are not fond of this current limitation, and with the public preview of restricting access to Azure Storage from SAS/Account Key, I suspect this will only increase over time.

**Comment by azfuncgh** [comment]
In an effort to clean up the repository, we're closing stale PRs. If you feel this is still relevant, please reopen the PR and we'll work on moving this forward. Thank you for your contribution!

**Pull request closed without merging**
