### PR TITLE
Queue Processing Extensibility

### PR DESCRIPTION
**Pull request by mathewc**
Adding adding a QueueProcessor strategy pattern to JobHostQueuesConfiguration, allowing users to override our default processing logic. This work addresses issues #510 and #505.

Features include:

* Ability to define a QueueProcessor per queue. This is done by providing your own IQueueProcessorFactory implementation
* Derive from default QueueProcessor and only override aspects you need to customize. E.g., override ReleaseMessage to implement your own message visibility backoff strategy for failed messages
* Ability to fully customize the CloudQueue and it's CloudQueueClient per queue

### CODE REVIEW

**Comment by daniel-chambers** [comment]
I'd like to give a little feedback on this, if I may. :)

As someone who would want to inherit from `QueueProcessor` in order to do my own retry backoff policy, I'm looking at `CompleteProcessingMessageAsync` and I can see that it tells me the operation failed via the `succeeded` bool, but I can't see _why_ it failed (ie the exception).

In our particular scenario, the code that runs to process a queue message calls services that may either have transitive errors (in which case a fast retry with a backoff policy is desirable) or errors that indicate an unresolvable error (in which case putting the message in the poison queue immediately is desirable). Unfortunately, just a succeed/fail bool means I can't see what the cause of the problem was in order to react differently.

**Comment by mathewc** [comment]
I agree with you Daniel. I had actually considered that, but decided to keep things simple - I wasn't sure it was needed. However, the fact that you immediately questioned the same thing made me realize it was important :)

I just pushed an update that flows a new FunctionResult type through. You can access any exception via functionResult.Exception.

**Comment by mathewc** [comment]
Also, you can see an example of a custom QueueProcessorFactory/QueueProcessor in the end to end [functional tests here](https://github.com/Azure/azure-webjobs-sdk/blob/queues-extensibility/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs#L221)

**Comment by daniel-chambers** [comment]
Looks great! Thanks :)

You guys thinking of releasing any prerelease Nuget packages so we can play with the bits ahead of an official stable release?

**Comment by mathewc** [comment]
Yes - actually I've already released these changes to the new App Service myget feed that I created recently :) https://www.myget.org/gallery/azure-appservice. This feed also contains the new WebJobs.Extensions package containing new out of band binding extensions that leverage all the new extensibility.

**Comment by daniel-chambers** [comment]
Awesome. Cheers. :)

**Pull request merged**
