### PR TITLE
Fix "Search for blobs" link in dashboard.

### PR DESCRIPTION
**Pull request by MikeStall**
Fix "About link" - it was showing indexing errors.

https://github.com/Azure/azure-webjobs-sdk/issues/840
https://github.com/Azure/azure-webjobs-sdk/issues/677

### CODE REVIEW

**Comment by mathewc** [comment]
How can we add regression tests that ensure all the configurations we're making on the "fast logger" app init path? We either need some unit tests (less expensive) that verify this, or perhaps some Dashboard UI tests (more expensive) that verify this.

**Comment by mathewc** [comment]
Is this review still active? I was wondering if there are any tests in place for this stuff. That would be ideal. I'm OK with just getting this fix in if you think adding tests will be too hard, but I really think we need them.

**Comment by MikeStall** [comment]
It's still active. It got pushed to the back burner while I tried to think how to test it. I agree we need some strong testing.

**Comment by MikeStall** [comment]
I've filed https://github.com/Azure/azure-webjobs-sdk/issues/857 and assigned to me to track the testing issues. I'll go ahead and push this fix since it's a small delta but fixes some obvious things.

**Pull request merged**
