### PR TITLE
Improve code and performance (Issue #2689)

### PR DESCRIPTION
**Pull request by Shazhko-Artem**
Addresses [#2689](https://github.com/Azure/azure-webjobs-sdk/issues/2689)
Please see the description there.

### CODE REVIEW

**Comment by Shazhko-Artem** [comment]
The solution was successfully built, but I can't figure out what the problem is with **vstest.console**. Looks like it's a pipeline setup problem.
image

**Comment by cgillum** [comment]
FYI @fabiocav @mathewc

**Review by mathewc — APPROVED** [review]
Looks good to me - thanks for improving this :)

**Comment by Shazhko-Artem** [comment]
Thank you @mathewc, I am very happy to make this improvement. I think I will continue to improve individual parts and offer new functionality.

**Review by fabiocav — APPROVED** [review]

**Comment by fabiocav** [comment]
Indeed! Thank you. Merging.

**Pull request merged**
