### PR TITLE
Logging resource accesses when binding function parameters.

### PR DESCRIPTION
**Pull request by gohar94**
This PR adds logging for resources accessed during function parameter binding.

Example logging output (queue trigger):

```
Binding Information:
BindingData:
QueueTrigger:  works
DequeueCount: 1
ExpirationTime: 8/3/2020 5:01:15 PM +00:00
Id: 76379388-cf1f-47b8-bced-1f83d46a4b7a
InsertionTime: 7/27/2020 5:01:15 PM +00:00
NextVisibleTime: 7/27/2020 5:11:17 PM +00:00
PopReceipt: AgAAAAMAAAAAAAAAV9OZ8Dhk1gE=
sys: Microsoft.Azure.WebJobs.Host.Bindings.SystemBindingData
ValueProviders:
InvokeString:  works, ValueType: System.String, BinderType: Microsoft.Azure.WebJobs.Host.Queues.Triggers.QueueMessageValueProvider
InvokeString: asynce2eq205f3a61b8fad403ba2258c37057d1832, ValueType: Microsoft.Azure.WebJobs.IAsyncCollector`1[System.String], BinderType: Microsoft.Azure.WebJobs.Host.Bindings.AsyncCollectorValueProvider`2[Microsoft.Azure.WebJobs.IAsyncCollector`1[System.String],System.String]
InvokeString: , ValueType: System.Threading.CancellationToken, BinderType: Microsoft.Azure.WebJobs.Host.Bindings.Cancellation.CancellationTokenValueProvider
InvokeString: , ValueType: Microsoft.Azure.WebJobs.Host.TraceWriter, BinderType: Microsoft.Azure.WebJobs.Host.Bindings.TraceWriterBinding+ValueBinder
```

Example logging output (blob trigger):

```
Binding Information:
BindingData:
BlobTrigger: asynce2e05f3a61b8fad403ba2258c37057d1832/Blob1
Uri: https://gochaudhstorage001.blob.core.windows.net/asynce2e05f3a61b8fad403ba2258c37057d1832/Blob1
Properties: Microsoft.Azure.Storage.Blob.BlobProperties
Metadata: System.Collections.Generic.Dictionary`2[System.String,System.String]
sys: Microsoft.Azure.WebJobs.Host.Bindings.SystemBindingData
ValueProviders:
InvokeString: asynce2e05f3a61b8fad403ba2258c37057d1832/Blob1, ValueType: System.IO.Stream, BinderType: Microsoft.Azure.WebJobs.Host.Bindings.ConstantValueProvider
InvokeString: asynce2e05f3a61b8fad403ba2258c37057d1832/Blob1, ValueType: System.String, BinderType: Microsoft.Azure.WebJobs.Host.Bindings.ObjectValueProvider
InvokeString: https://gochaudhstorage001.blob.core.windows.net/asynce2e05f3a61b8fad403ba2258c37057d1832/Blob1, ValueType: System.Uri, BinderType: Microsoft.Azure.WebJobs.Host.Bindings.ObjectValueProvider
InvokeString: System.Collections.Generic.Dictionary`2[System.String,System.String], ValueType: System.Collections.Generic.IDictionary`2[System.String,System.String], BinderType: Microsoft.Azure.WebJobs.Host.Bindings.ObjectValueProvider
InvokeString: Microsoft.Azure.Storage.Blob.BlobProperties, ValueType: Microsoft.Azure.Storage.Blob.BlobProperties, BinderType: Microsoft.Azure.WebJobs.Host.Bindings.ObjectValueProvider
InvokeString: asynce2e05f3a61b8fad403ba2258c37057d1832/Blob2, ValueType: System.IO.Stream, BinderType: Microsoft.Azure.WebJobs.Host.Bindings.BindToStreamBindingProvider`1+ValueProvider`1[Microsoft.Azure.WebJobs.BlobAttribute,System.IO.Stream]
InvokeString: , ValueType: System.Threading.CancellationToken, BinderType: Microsoft.Azure.WebJobs.Host.Bindings.Cancellation.CancellationTokenValueProvider
```

### CODE REVIEW

**Comment by paulbatum** [comment]
Few inital thoughts:
1. I am not sure if we should be capturing the actual storage account name (gochaudhstorage001 in your above example).
2. These logs seem noisy. Not sure what the point is of the invoke string entries, particular ones for cancellation token, tracewriter etc. I assume this is a result of the implementation being very generic? If so I think the implementation needs to become more specific.
3. I get the value of some of the information here for blob, but what about queue? The useful parts are dequeue count, insertion time, next visible time,etc but I think we have some of that already logged (at least, I'm pretty sure dequeue count is..). We should avoid capturing the same information multiple times in different log entries.

**Comment by gohar94** [comment]
@paulbatum 

1. Yes, we can remove that part of the Uri.
2. The idea was to keep the implementation simple/generic so yes, that's why we are capturing more of that information. Should we implement this elsewhere then? Perhaps the storage extension itself and specifically do it for blob?
3. I am not sure what information for queues is already being logged but it would definitely be helpful to capture some of the properties (like the ones you mentioned) - can we confirm what we are logging already and maybe log the remaining ones? And that also should be done in the storage extension then?

**Comment by pragnagopa** [comment]
> Should we implement this elsewhere then? Perhaps the storage extension itself and specifically do it for blob?

I recommend extension specific logging. This will ensure each extension can control log-entries  and only log information that is useful for tracking which resources are being accessed specific to that binding.

In the above example, for blob trigger URI is useful but that does not apply to queue trigger.

**Comment by gohar94** [comment]
@pragnagopa As per your feedback, I've opened another PR [here](https://github.com/Azure/azure-webjobs-sdk/pull/2557).

**Comment by pragnagopa** [comment]
Closing in favor of #2557

**Pull request closed without merging**
