### PR TITLE
Add link to GitHub repo releases page to nuspec Release Notes

### PR DESCRIPTION
**Pull request by colbylwilliams**
Added link to this repo's releases page as this is where we're adding release notes and it takes unnecessary searching to find them from the NuGet page

### CODE REVIEW

**Comment by mathewc** [comment]
@colbylwilliams are you planning on merging this, or do you want us to? Also, please sign the CLA.

**Comment by colbylwilliams** [comment]
@mathewc feel free to merge, but I can tomorrow if it isn’t merged already.  CLA should already be signed...?

**Comment by colbylwilliams** [comment]
@mathewc actually doesn’t look like I have write access, so I can’t merge.

**Comment by mathewc** [comment]
Merged, thanks :)

**Pull request closed without merging**
