### PR TITLE
bumping version number

### PR DESCRIPTION
**Pull request by brettsam**

### CODE REVIEW

**Comment by brettsam** [comment]
@mathewc -- quick look at this? We should be bumping up right after a release (rather than right before) so our MyGet packages look newer. We just rarely do that :-)

**Comment by mathewc** [comment]
Funny - I just did this for v2 https://github.com/Azure/azure-webjobs-sdk/commit/5759fc792190eb9da07b5300d976d2275d1e7168

**Comment by mathewc** [comment]
What about all the other packages, e.g. Extensions?

**Comment by brettsam** [comment]
Will do extensions as well.

**Pull request merged**
